name: ${project.name}
main: ${project.groupId}.${project.artifactId}.${project.name}Plugin
version: ${project.version}
authors: [SpaceEmotion, portalBlock]

commands:
   game:
      description: Main Plugin Command.
      usage: /game
